# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('surname', models.CharField(max_length=256, verbose_name='Surname')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Woman', 'Women')], default='Men', max_length=5, verbose_name='Gender')),
                ('barcode', models.IntegerField(default='0', verbose_name='Barcode')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('number', models.IntegerField(default='0', verbose_name='Number on list')),
            ],
        ),
        migrations.CreateModel(
            name='GameCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.IntegerField(default='0', verbose_name='Barcode')),
                ('weight', models.IntegerField(default='0', verbose_name='Weight')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('state', models.CharField(choices=[('Loaned', 'Loaned'), ('Free', 'Free')], default='Free', max_length=6, verbose_name='State')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservationSystemApp.Game')),
            ],
        ),
    ]
