# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ReservationSystemApp', '0003_gamecopy_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCopyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Loaned', 'Loaned'), ('Free', 'Free')], default='Free', max_length=6, verbose_name='State')),
                ('dateTime', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservationSystemApp.Client', verbose_name='Client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservationSystemApp.Event', verbose_name='Event')),
                ('gameCopy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservationSystemApp.GameCopy', verbose_name='Game Copy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
        ),
    ]
