# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationSystemApp', '0004_gamecopyhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecopyhistory',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
