# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-03 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationSystemApp', '0007_auto_20180703_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecopy',
            name='rentalDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
