# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-03 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationSystemApp', '0010_auto_20180703_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='paymentCategory',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ReservationSystemApp.PaymentCategories', verbose_name='Kategoria cenowa'),
        ),
    ]
