# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-03 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationSystemApp', '0011_game_paymentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecopy',
            name='cost',
            field=models.IntegerField(default='0', verbose_name='Cena'),
        ),
    ]
